# Generated by Django 5.2.8 on 2026-01-11 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacher_date_of_joining_teacher_dob_teacher_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('test_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assignment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
