# Generated by Django 5.2.8 on 2026-01-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_internalmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalmark',
            old_name='test_1',
            new_name='test_1_scored',
        ),
        migrations.RenameField(
            model_name='internalmark',
            old_name='test_2',
            new_name='test_2_scored',
        ),
        migrations.AddField(
            model_name='internalmark',
            name='test_1_total',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='internalmark',
            name='test_2_total',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
