# Generated by Django 5.2.8 on 2026-01-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_test_1_internalmark_test_1_scored_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalmark',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='internalmark',
            name='attendance_score',
        ),
    ]
