# Generated by Django 5.2.8 on 2026-03-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_studynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studynote',
            name='description',
        ),
    ]
